# Generated by Django 5.2 on 2025-04-24 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="store_produ_id_2abda1_idx",
            old_fields=("id", "slug"),
        ),
    ]
